/* This file was generated by syncqt. */
#ifndef QT_QTDESIGNER_VERSION_H
#define QT_QTDESIGNER_VERSION_H

#define QTDESIGNER_VERSION_STR "6.9.3"

#define QTDESIGNER_VERSION 0x060903

#endif // QT_QTDESIGNER_VERSION_H
